# Generated by Django 5.2.10 on 2026-01-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='role',
            new_name='roles_role_na_cfef50_idx',
            old_name='roles_role_n_idx',
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='user_roles_user_id_801a9e_idx',
            old_name='user_roles_user_id_role_id_idx',
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='user_roles_role_id_0b583b_idx',
            old_name='user_roles_role_id_idx',
        ),
    ]
