# Generated by Django 5.2.10 on 2026-02-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_data', '0003_rename_locations_district_area_idx_locations_distric_d2cbe7_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(max_length=50, verbose_name='Period Type')),
                ('baseline_method', models.CharField(max_length=50, verbose_name='Baseline Method')),
                ('baseline_value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Baseline Value')),
                ('computed_for_start', models.DateField(verbose_name='Computed For Start')),
                ('computed_for_end', models.DateField(verbose_name='Computed For End')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='Computed At')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_metrics', to='reference_data.disease', verbose_name='Disease')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_metrics', to='reference_data.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Baseline Metric',
                'verbose_name_plural': 'Baseline Metrics',
                'db_table': 'baseline_metrics',
                'ordering': ['-computed_for_end', 'disease_id', 'location_id'],
                'indexes': [models.Index(fields=['disease', 'location', 'computed_for_start', 'computed_for_end'], name='baseline_me_disease_71a023_idx'), models.Index(fields=['period_type', 'baseline_method'], name='baseline_me_period__203275_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrendMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('total_cases', models.PositiveIntegerField(verbose_name='Total Cases')),
                ('moving_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Moving Average')),
                ('pct_change', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Percent Change')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='Computed At')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trend_metrics', to='reference_data.disease', verbose_name='Disease')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trend_metrics', to='reference_data.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Trend Metric',
                'verbose_name_plural': 'Trend Metrics',
                'db_table': 'trend_metrics',
                'ordering': ['-period_end', 'disease_id', 'location_id'],
                'indexes': [models.Index(fields=['disease', 'location', 'period_start', 'period_end'], name='trend_metri_disease_d6a5f2_idx'), models.Index(fields=['computed_at'], name='trend_metri_compute_54a94e_idx')],
            },
        ),
    ]
