# Generated by Django 5.2.10 on 2026-02-07 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Due At')),
                ('task_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=20, verbose_name='Task Status')),
                ('outcome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outcome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_tasks', to='alerts.alert', verbose_name='Alert')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
            ],
            options={
                'verbose_name': 'Investigation Task',
                'verbose_name_plural': 'Investigation Tasks',
                'db_table': 'investigation_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert'], name='investigati_alert_i_6a2c06_idx'), models.Index(fields=['assigned_to'], name='investigati_assigne_81ceca_idx'), models.Index(fields=['task_status'], name='investigati_task_st_633b94_idx')],
            },
        ),
    ]
