GREATER_ACCRA_DISTRICT_NAMES = [
    "Accra Metropolitan",
    "Tema Metropolitan",
    "Ga East Municipal",
    "Ga West Municipal",
    "Ga South Municipal",
    "La Dade-Kotopon Municipal",
    "Ledzokuku Municipal",
    "Adenta Municipal",
    "Ashaiman Municipal",
    "Kpone Katamanso Municipal",
    "Ningo-Prampram District",
    "Shai-Osudoku District",
    "Weija-Gbawe Municipal",
    "Ablekuma North Municipal",
    "Ablekuma Central Municipal",
    "Ablekuma West Municipal",
    "Ayawaso West Municipal",
    "Ayawaso East Municipal",
    "Ayawaso North Municipal",
    "Ayawaso Central Municipal",
    "Okaikwei North Municipal",
    "Korle-Klottey Municipal",
]
