# Generated by Django 5.2.10 on 2026-02-07 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_data', '0003_rename_locations_district_area_idx_locations_distric_d2cbe7_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Status Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Report Status',
                'verbose_name_plural': 'Report Statuses',
                'db_table': 'report_status',
                'ordering': ['status_name'],
                'indexes': [models.Index(fields=['status_name'], name='report_stat_status__6cdd1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='Observed At')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('case_notes', models.TextField(blank=True, verbose_name='Case Notes')),
                ('report_source', models.CharField(blank=True, max_length=20, null=True, verbose_name='Report Source')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reference_data.disease', verbose_name='Disease')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reference_data.location', verbose_name='Location')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reported By')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reporting.reportstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_reason', models.TextField(verbose_name='Flagged Reason')),
                ('flagged_at', models.DateTimeField(auto_now_add=True, verbose_name='Flagged At')),
                ('review_outcome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Review Outcome')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_duplicate_flags', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags', to='reporting.report', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Duplicate Flag',
                'verbose_name_plural': 'Duplicate Flags',
                'db_table': 'duplicate_flags',
                'ordering': ['-flagged_at'],
                'indexes': [models.Index(fields=['report'], name='duplicate_f_report__05d951_idx'), models.Index(fields=['reviewed_by'], name='duplicate_f_reviewe_87bf2f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['disease', 'location', 'observed_at'], name='reports_disease_49d8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_status__259940_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_by'], name='reports_reporte_e16096_idx'),
        ),
    ]
