# Generated by Django 5.2.10 on 2026-02-07 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0003_rename_locations_district_area_idx_locations_distric_d2cbe7_idx'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='age_group',
            field=models.CharField(choices=[('UNDER_5', 'Under 5'), ('AGE_5_17', '5-17'), ('AGE_18_59', '18-59'), ('AGE_60_PLUS', '60+'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=20, verbose_name='Age Group'),
        ),
        migrations.AddField(
            model_name='report',
            name='case_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of suspected cases in this report', verbose_name='Case Count'),
        ),
        migrations.AddField(
            model_name='report',
            name='severity_level',
            field=models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20, verbose_name='Severity Level'),
        ),
        migrations.AddField(
            model_name='report',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=20, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='observed_at',
            field=models.DateTimeField(db_index=True, verbose_name='Observed At'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['sex'], name='reports_sex_4d4b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['age_group'], name='reports_age_gro_3ebe92_idx'),
        ),
    ]
