# Generated by Django 5.2.10 on 2026-02-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100, verbose_name='Action Type')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Entity Type')),
                ('entity_id', models.CharField(max_length=255, verbose_name='Entity ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Details')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor_user'], name='audit_logs_actor_u_6a2681_idx'), models.Index(fields=['entity_type'], name='audit_logs_entity__4f758f_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF')], max_length=10, verbose_name='Export Type')),
                ('filters_used', models.JSONField(blank=True, null=True, verbose_name='Filters Used')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='File Path')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
            ],
            options={
                'verbose_name': 'Export',
                'verbose_name_plural': 'Exports',
                'db_table': 'exports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['generated_at'], name='exports_generat_5349cf_idx'), models.Index(fields=['export_type'], name='exports_export__4d4395_idx')],
            },
        ),
    ]
