from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class Export(models.Model):
    """
    Model representing export metadata for CSV/PDF file generation.

    This model stores metadata about export requests, not the file contents.
    It is designed to support asynchronous export processing via Celery tasks
    in future implementations, allowing long-running exports without blocking
    the web request.
    """

    class ExportType(models.TextChoices):
        """Export file format choices."""

        CSV = "CSV", _("CSV")
        PDF = "PDF", _("PDF")

    class ExportStatus(models.TextChoices):
        """Export processing status choices."""

        PENDING = "PENDING", _("Pending")
        COMPLETED = "COMPLETED", _("Completed")
        FAILED = "FAILED", _("Failed")

    export_type = models.CharField(
        _("Export Type"),
        max_length=10,
        choices=ExportType.choices,
    )
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="exports",
        verbose_name=_("Generated By"),
    )
    filters_used = models.JSONField(_("Filters Used"), blank=True, null=True)
    generated_at = models.DateTimeField(_("Generated At"), auto_now_add=True)
    file_path = models.CharField(_("File Path"), max_length=500, blank=True, null=True)
    status = models.CharField(
        _("Status"),
        max_length=20,
        choices=ExportStatus.choices,
        default=ExportStatus.PENDING,
    )

    class Meta:
        db_table = "exports"
        verbose_name = _("Export")
        verbose_name_plural = _("Exports")
        ordering = ["-generated_at"]
        indexes = [
            models.Index(fields=["generated_at"]),
            models.Index(fields=["export_type"]),
        ]

    def __str__(self) -> str:
        """Return readable string representation."""
        user_str = (
            self.generated_by.email if self.generated_by else "Unknown User"
        )
        return f"{self.export_type} export by {user_str} ({self.status})"


class AuditLog(models.Model):
    """
    Model representing audit logs for system-level actions.

    This model tracks critical system actions to enable traceability and
    accountability. It records events but does not enforce business logic.
    Use this for logging user actions, data changes, and system events
    that require audit trails for compliance and debugging.
    """

    actor_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="audit_logs",
        verbose_name=_("Actor User"),
    )
    action_type = models.CharField(_("Action Type"), max_length=100)
    entity_type = models.CharField(_("Entity Type"), max_length=100)
    entity_id = models.CharField(_("Entity ID"), max_length=255)
    timestamp = models.DateTimeField(_("Timestamp"), auto_now_add=True)
    details = models.JSONField(_("Details"), blank=True, null=True)

    class Meta:
        db_table = "audit_logs"
        verbose_name = _("Audit Log")
        verbose_name_plural = _("Audit Logs")
        ordering = ["-timestamp"]
        indexes = [
            models.Index(fields=["actor_user"]),
            models.Index(fields=["entity_type"]),
            models.Index(fields=["timestamp"]),
        ]

    def __str__(self) -> str:
        """Return readable string representation."""
        actor_str = (
            self.actor_user.email if self.actor_user else "System"
        )
        return f"{self.action_type} on {self.entity_type} by {actor_str}"


def record_audit_event(*, actor, action_type, entity_type, entity_id, details=None):
    return AuditLog.objects.create(
        actor_user=actor if getattr(actor, "is_authenticated", False) else None,
        action_type=action_type,
        entity_type=entity_type,
        entity_id=str(entity_id),
        details=details or {},
    )

