# Generated by Django 5.2.10 on 2026-02-07 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0002_rename_roles_role_n_idx_roles_role_na_cfef50_idx_and_more'),
        ('reference_data', '0003_rename_locations_district_area_idx_locations_distric_d2cbe7_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Status Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Alert Status',
                'verbose_name_plural': 'Alert Statuses',
                'db_table': 'alert_status',
                'ordering': ['status_name'],
                'indexes': [models.Index(fields=['status_name'], name='alert_statu_status__af5460_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(verbose_name='Period Start')),
                ('period_end', models.DateTimeField(verbose_name='Period End')),
                ('baseline_value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Baseline Value')),
                ('observed_value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Observed Value')),
                ('threshold_rule', models.TextField(verbose_name='Threshold Rule')),
                ('severity_level', models.CharField(max_length=50, verbose_name='Severity Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='reference_data.disease', verbose_name='Disease')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='reference_data.location', verbose_name='Location')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.alertstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_reason', models.TextField(verbose_name='Escalation Reason')),
                ('escalated_at', models.DateTimeField(auto_now_add=True, verbose_name='Escalated At')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='alerts.alert', verbose_name='Alert')),
                ('escalated_from_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations_from', to='access_control.role', verbose_name='Escalated From Role')),
                ('escalated_to_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations_to', to='access_control.role', verbose_name='Escalated To Role')),
            ],
            options={
                'verbose_name': 'Alert Escalation',
                'verbose_name_plural': 'Alert Escalations',
                'db_table': 'alert_escalations',
                'ordering': ['-escalated_at'],
                'indexes': [models.Index(fields=['alert', 'escalated_at'], name='alert_escal_alert_i_34ab2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(verbose_name='Note Text')),
                ('noted_at', models.DateTimeField(auto_now_add=True, verbose_name='Noted At')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='alerts.alert', verbose_name='Alert')),
                ('noted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_notes', to=settings.AUTH_USER_MODEL, verbose_name='Noted By')),
            ],
            options={
                'verbose_name': 'Alert Note',
                'verbose_name_plural': 'Alert Notes',
                'db_table': 'alert_notes',
                'ordering': ['-noted_at'],
                'indexes': [models.Index(fields=['alert'], name='alert_notes_alert_i_281dbc_idx'), models.Index(fields=['noted_by'], name='alert_notes_noted_b_ee1cd4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['disease', 'location'], name='alerts_disease_ae5e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity_level'], name='alerts_status__a3836e_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='alerts_created_965da5_idx'),
        ),
    ]
