# Generated by Django 5.2.10 on 2026-01-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'locations',
                'indexes': [models.Index(fields=['district_name', 'area_name'], name='locations_district_area_idx')],
            },
        ),
    ]
