# Generated by Django 5.2.10 on 2026-01-28 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_location'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='location',
            new_name='locations_distric_d2cbe7_idx',
            old_name='locations_district_area_idx',
        ),
    ]
