# Generated by Django 5.2.10 on 2026-03-01 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0003_rename_locations_district_area_idx_locations_distric_d2cbe7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='population',
            field=models.IntegerField(blank=True, help_text='District population from 2021 census', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='location',
            name='population_year',
            field=models.IntegerField(default=2021, help_text='Census year for the population figure'),
        ),
    ]
